name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      XDEBUG_MODE: coverage
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
      - uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          php_extensions: mbstring
          version: 2.x
      
      - name: run PHPUnit tests
        run: ./vendor/bin/phpunit --testdox --coverage-clover coverage.xml
          
      - name: Run PHP_CodeSniffer
        run: ./vendor/bin/phpcs
          
      - name: Generate test coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          report_type: clover
          report: 'coverage.xml'
          coverage_badge_path: 'badge.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
